language: php

php:
  - 7.2

matrix:
  fast_finish: true

before_script:
  - sudo apt-get update
  - sudo apt-get install -y imagemagick
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick
  - composer install

script: vendor/bin/phpunit
